language: python

cache: pip

python:
  - "3.7"

addons:
  apt:
    packages:
      - verilator
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev

install:
  - pip install pytest fault pytest-codestyle 
  - pip install -e .

script:
  - pytest --pycodestyle -v tests/


notifications:
  email:
    on_success: never # default: change
