name: rtl

outputs:
  - design.v
  - testbench.sv
  - design.args

commands:

  - export CURR=$PWD
  - echo $CURR

  - git clone https://github.com/StanfordAHA/lake/
  - cd lake
  - git checkout new_asplos
  - export TOP=$PWD

  - python3.7 -m venv lake_env
  - source lake_env/bin/activate
  - python -m pip install --upgrade pip
  - pip install -e .

  - python tests/test_spec/simple_dual_port.py --reg_file --physical

  - cd $CURR
  - cp $TOP/TEST/inputs/lakespec.sv outputs/design.v
  - cp $TOP/tests/test_spec_hw/tb.sv outputs/testbench.sv
  - cat $TOP/TEST/inputs/comp_args.txt $TOP/TEST/inputs/PARGS.txt > outputs/design.args
  - cp $TOP/TEST/inputs/comp_args.txt outputs/design.args
  
  - echo $PWD
  
