name: rtl

outputs:
  - design.v
  - testbench.sv
  - design.args
  - info.json

commands:

  - export CURR=$PWD
  - echo $CURR

  - git clone https://github.com/StanfordAHA/lake/
  - cd lake
  - git checkout new_asplos
  - export TOP=$PWD

  - python3.7 -m venv lake_env
  - source lake_env/bin/activate
  - python -m pip install --upgrade pip
  - pip install -e .

  - python tests/test_spec/dual_port_rv.py --reg_file --storage_capacity 32 --dimensionality 4 --physical --clock_count_width 32

  - cd $CURR
  - cp $TOP/TEST/inputs/lakespec.sv outputs/design.v
  - cp $TOP/tests/test_spec_hw/tb.sv outputs/testbench.sv
  - cat $TOP/TEST/inputs/comp_args.txt $TOP/TEST/inputs/PARGS.txt > outputs/design.args

  - python set_test_dir.py

  - echo $PWD

