#=========================================================================
# Creating images for lake specs
#=========================================================================
# Author : Marc Huerta
#

name: signoff_area_plotting

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - signoff.area.rpt

outputs:
  - images/

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
parameters:
  design_name: lakespec

commands: 
  - python3 area_rpt_to_csv.py
  - cp -r ./images ./outputs/


#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------


postconditions:
  - assert File( 'outputs/images/' )       # must exist
