#=========================================================================
# Creating images for lake specs
#=========================================================================
# Author : Marc Huerta
#

name: signoff_area_plotting

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - signoff.area.rpt

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

commands: 
  - python3 area_rpt_to_csv.py
