name: rtl

outputs:
  - design.v

commands:

  - export CURR=$PWD
  - echo $CURR

  - git clone https://github.com/StanfordAHA/lake/
  - cd lake
  - git checkout new_asplos
  - export TOP=$PWD

  - python3.7 -m venv lake_env
  - source lake_env/bin/activate
  - python -m pip install --upgrade pip
  - pip install -e .

  - python tests/test_spec/simple_dual_port.py --data_width 16 --storage_capacity 1024 --physical

  - cd $CURR
  - mv $TOP/TEST/inputs/lakespec.sv outputs/design.v
  - echo $PWD
  